name: Android Release CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Decode keystore
        run: echo "${{ secrets.SIGNING_STORE_BASE64 }}" | base64 --decode > android/app/release.keystore

      - name: Build Release APK
        run: ./gradlew assembleRelease -Pandroid.injected.signing.store.file=android/app/release.keystore \
            -Pandroid.injected.signing.store.password="${{ secrets.SIGNING_STORE_PASSWORD }}" \
            -Pandroid.injected.signing.key.alias="${{ secrets.SIGNING_KEY_ALIAS }}" \
            -Pandroid.injected.signing.key.password="${{ secrets.SIGNING_KEY_PASSWORD }}"

      - name: Upload signed APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: tft-ai-coach-signed-apk
          path: android/app/build/outputs/apk/release/app-release.apk
