name: Build Android Debug APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Pegar o código
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurar JDK 17
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 3. Dar permissão de execução para gradlew
      - name: Give gradlew permission
        run: chmod +x android/gradlew

      # 4. Build APK debug
      - name: Build Debug APK
        run: |
          cd android
          ./gradlew assembleDebug --stacktrace --info --warning-mode all

      # 5. Listar outputs para debug
      - name: List build outputs
        run: ls -alR android/app/build/outputs/ || true

      # 6. Upload do APK debug
