name: Build Android Debug APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurar JDK 17
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 3. Verificar se a pasta android/app existe
      - name: Check android/app folder
        run: |
          if [ ! -d "android/app" ]; then
            echo "android/app does not exist. Skipping build."
            exit 0
          fi

      # 4. Dar permissão de execução para gradlew, se existir
      - name: Give gradlew permission
        run: |
          if [ -f "android/gradlew" ]; then
            chmod +x android/gradlew
          else
            echo "gradlew not found. Skipping build."
            exit 0
          fi

      # 5. Build Debug APK
      - name: Build Debug APK
        run: |
          cd android
          ./gradlew assembleDebug --stacktrace --info --warning-mode all

      # 6. Listar todos os APKs gerados
      - name: Find APKs
        run: |
          echo "Looking for APKs..."
          find android/app/build/outputs/ -name "*.apk" || echo "No APKs found"

      # 7. Upload de qualquer APK gerado
      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-apk
          path: android/app/build/outputs/**/*.apk
