name: Build Android App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Pegar o código do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurar JDK para Android
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Garantir permissão de execução do gradlew
      - name: Make gradlew executable
        run: chmod +x android/gradlew

      # 4. Build do app (APK ou AAB)
      - name: Build Android App
        run: |
          cd android
          ./gradlew clean assembleRelease --stacktrace --no-daemon

      # 5. Debug: listar todos os outputs (APK ou AAB)
      - name: List build outputs
        run: ls -alR android/app/build/outputs/ || true

      # 6. Upload de APK ou AAB (qualquer formato gerado)
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-build
          path: android/app/build/outputs/**/*.{apk,aab}
