name: Build Android Debug APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: /usr/local/android-sdk

    steps:
      # 1. Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up JDK 17
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 3. Install required Android SDK packages
      - name: Install Android SDK
        run: |
          sudo mkdir -p $ANDROID_SDK_ROOT
          sudo chown $USER:$USER $ANDROID_SDK_ROOT
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d $ANDROID_SDK_ROOT/cmdline-tools
          mv $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      # 4. Dar permissão de execução para gradlew
      - name: Give gradlew permission
        run: chmod +x android/gradlew

      # 5. Build Debug APK
      - name: Build Debug APK
        run: |
          cd android
          ./gradlew assembleDebug --stacktrace --info --warning-mode all

      # 6. Mostrar todos os APKs gerados
      - name: Find APKs
        run: |
          echo "Looking for APKs..."
          find android/app/build/outputs/ -name "*.apk" || echo "No APKs found"

      # 7. Upload de qualquer APK gerado
      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-apk
          path: android/app/build/outputs/**/*.apk
